apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-webapp
  name: react-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-webapp
    spec:
      containers:
      - image: '<+artifact.image>'
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 80 
status: {}
