apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: index.docker.io/psuholet/deluxe-pov-image-from-example:latest
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5000
