apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
    - image: {{.Values.image}}
      name: webapp
      imagePullPolicy: Always
      resources: {}
      ports:
        - containerPort: 5000
